name: Tests
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          path: r-client
      - uses: actions/setup-node@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          path: r-client

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          path: r-client

      - uses: actions/checkout@v6
        with:
          repository: moregeo-it/openeo-test-api
          path: test-api
      - name: setup and run test-api
        working-directory: test-api
        run: | 
          npm install
          npm run adduser js-client js-client
          npm run up

      - name: install openeo package
        working-directory: js-client 
        run: R CMD INSTALL --preclean --no-multiarch --with-keep.source openeo-r-client      

      - name: Test R client
        working-directory: js-client 
        run: R -f tests/testthat.R